import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "AI Email & SMS Campaigns | Shark Branding Solutions",
  description:
    "AI-powered email and SMS marketing campaigns that nurture leads, re-engage past customers, and drive repeat business, all running automatically in the background.",
  alternates: {
    canonical: "https://sharkbrandingsolutions.com/campaigns",
  },
  openGraph: {
    title: "AI Email & SMS Campaigns | Shark Branding Solutions",
    description:
      "Automated email and SMS campaigns that keep your business top of mind and drive repeat business without extra work.",
    url: "https://sharkbrandingsolutions.com/campaigns",
  },
};

const CDN = "https://cdn-bjmjf.nitrocdn.com/gsSJVsHgkwexdOuGJbPveYehDehaVtlN/assets/images/optimized/rev-9db17f0/www.vendasta.com/wp-content/uploads/";

const features = [
  {
    id: "ai",
    h2: "AI-powered campaigns that write, send, and optimize themselves",
    body: "Our AI campaign engine analyzes your customer data, picks the right message, sends it at the right time, and adjusts based on results. You approve the strategy once. The system handles execution.\n\nNo more manually writing emails or guessing the best time to send. AI handles the heavy lifting while you focus on running your business.",
    cta: { label: "See how AI campaigns work", href: "/aiemployees" },
    img: CDN + "2018/08/ai-campaigns-1-567x.png",
    alt: "AI campaigns dashboard showing automated email and SMS sequences with performance analytics",
    imgLeft: false,
    width: 567,
    height: 370,
  },
  {
    id: "email",
    h2: "Professional email campaigns without the agency price tag",
    body: "From welcome sequences to re-engagement flows, our platform provides ready-made email templates built for local businesses. Customized to your brand, your offers, and your customer journey.\n\nDesign once, run forever. Automated drip sequences keep your business top of mind for every lead in your database without any ongoing manual work.",
    cta: { label: "Explore email marketing", href: "/services" },
    img: CDN + "2018/08/Group-48721-1-502x.png",
    alt: "Email campaign builder showing drag-and-drop template editor with live preview",
    imgLeft: true,
    width: 502,
    height: 387,
  },
  {
    id: "sms",
    h2: "SMS campaigns with open rates email can't match",
    body: "98% of text messages are read within 3 minutes. Our SMS campaign tools let you send appointment reminders, promotional offers, and follow-ups directly to your customers' phones.\n\nAutomate texts based on triggers, send targeted broadcasts to specific customer segments, or run coordinated email and SMS sequences together for maximum impact.",
    cta: { label: "Learn about SMS marketing", href: "/services" },
    img: CDN + "2018/08/Group-48722-1-502x.png",
    alt: "SMS campaign interface showing text message templates and automated send sequences",
    imgLeft: false,
    width: 502,
    height: 406,
  },
  {
    id: "automation",
    h2: "Set it once. Run it forever.",
    body: "Automation sequences trigger based on customer behavior. New lead fills out your form? They get a welcome sequence. Customer hasn't visited in 60 days? A re-engagement campaign starts automatically.\n\nEvery touchpoint in your customer lifecycle can be automated with campaigns built specifically for local service businesses.",
    cta: { label: "See automation examples", href: "/contact" },
    img: CDN + "2018/08/Group-48735-1-502x.png",
    alt: "Marketing automation workflow showing trigger-based email and SMS sequences",
    imgLeft: true,
    width: 502,
    height: 460,
  },
  {
    id: "reporting",
    h2: "Know exactly what's working with real-time reporting",
    body: "Track open rates, click rates, conversions, and revenue generated by every campaign. Our reporting dashboard shows you which messages resonate, which segments convert best, and where to focus next.\n\nMonth-end reports delivered automatically show your campaign performance over time, so you can see the return on every dollar spent.",
    cta: { label: "See reporting features", href: "/contact" },
    img: CDN + "2018/08/Group-48754-1-502x.png",
    alt: "Campaign performance reporting dashboard showing open rates, clicks, and conversion metrics",
    imgLeft: false,
    width: 502,
    height: 364,
  },
  {
    id: "social",
    h2: "Connect campaigns to your social presence",
    body: "Coordinate your email campaigns with your social media posts for a consistent message across every channel. Our platform links campaign performance to social engagement so you can see the full picture.\n\nWhen a campaign drives website traffic, you see it. When social posts generate leads that enter a campaign, you see that too. One dashboard, full visibility.",
    cta: { label: "Explore social media tools", href: "/services" },
    img: CDN + "2018/08/Group-48762-1-502x.png",
    alt: "Multi-channel campaign view connecting email, SMS, and social media marketing",
    imgLeft: true,
    width: 502,
    height: 408,
  },
];

const channelCards = [
  {
    img: CDN + "2025/03/Email-and-SMS-Marketing-Icon.png",
    title: "Email & SMS",
    body: "Automated sequences and one-time broadcasts across email and text.",
  },
  {
    img: CDN + "2025/04/Social-media-content.png",
    title: "Social media",
    body: "Scheduled posts and paid campaign coordination across all major platforms.",
  },
  {
    img: CDN + "2025/04/Digital-advertising.png",
    title: "Digital advertising",
    body: "Google, Meta, and display ads managed and reported alongside your organic campaigns.",
  },
  {
    img: CDN + "2025/04/Listing-management-1.png",
    title: "Listing updates",
    body: "Campaign offers and promotions automatically pushed to your business listings.",
  },
];

const stats = [
  { value: "98%", label: "Average SMS open rate within 3 minutes of sending" },
  { value: "4x", label: "More revenue from automated campaigns vs one-time sends" },
  { value: "60%", label: "Of customers say they want to hear from local businesses via text" },
];

const testimonials = [
  {
    quote: "We set up a re-engagement campaign for customers who hadn't booked in 90 days. Within the first month it brought back 18 customers we thought we'd lost.",
    name: "Owner",
    company: "Auto service shop, Tampa FL",
  },
  {
    quote: "The welcome sequence alone pays for the platform. Every new lead gets a professional follow-up within minutes, not days. Our close rate went up immediately.",
    name: "Operations Manager",
    company: "Home services company, Wesley Chapel FL",
  },
  {
    quote: "I used to spend every Monday morning writing marketing emails. Now the system does it. I just check the report to see how they performed.",
    name: "Owner",
    company: "Med spa, Florida",
  },
];

export default function CampaignsPage() {
  return (
    <div className="bg-white">

      {/* HERO */}
      <section className="bg-[#07141a] py-20 px-6 overflow-hidden">
        <div className="max-w-[1200px] mx-auto flex flex-col lg:flex-row items-center gap-12 lg:gap-16 pt-8">
          <div className="flex-1 min-w-0">
            <span className="inline-block text-[#18b5d8] text-[13px] font-bold tracking-[2px] uppercase mb-5">
              AI Campaigns
            </span>
            <h1 className="text-[38px] sm:text-[50px] lg:text-[56px] font-extrabold text-white leading-[1.08] tracking-tight mb-6" style={{ textWrap: "balance" }}>
              Email and SMS campaigns that run themselves
            </h1>
            <p className="text-[#8d9aab] text-[18px] leading-relaxed mb-8 max-w-[520px]">
              AI-powered marketing campaigns that nurture leads, re-engage past customers, and drive repeat business, all running automatically while you focus on the work.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                href="/contact"
                className="inline-flex items-center justify-center bg-[#18b5d8] hover:bg-[#14a2c2] text-white font-bold text-[15px] px-8 py-4 rounded-full transition-colors duration-150"
              >
                Book a strategy call
              </Link>
              <Link
                href="/plans"
                className="inline-flex items-center justify-center bg-white/10 hover:bg-white/20 text-white font-semibold text-[15px] px-8 py-4 rounded-full transition-colors duration-150"
              >
                View pricing
              </Link>
            </div>
          </div>

          <div className="flex-1 min-w-0 w-full lg:max-w-[560px]">
            <div className="relative rounded-[20px] overflow-hidden shadow-2xl">
              <Image
                src={CDN + "2018/08/CampaignsPro-hero-542x.png"}
                alt="AI Campaigns Pro dashboard showing automated email and SMS marketing performance"
                width={542}
                height={510}
                className="w-full h-auto"
                priority
              />
            </div>
          </div>
        </div>
      </section>

      {/* STATS */}
      <section className="py-16 px-6 bg-[#f5f5f7] border-b border-[#e5e5ea]">
        <div className="max-w-[1000px] mx-auto grid sm:grid-cols-3 gap-8 text-center">
          {stats.map((s) => (
            <div key={s.value}>
              <p className="text-[48px] font-extrabold text-[#18b5d8] leading-none mb-2">{s.value}</p>
              <p className="text-[15px] text-[#6e6e73] leading-snug">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CHANNELS — 4 cards */}
      <section className="py-20 px-6 border-b border-[#e5e5ea]">
        <div className="max-w-[1200px] mx-auto">
          <h2 className="text-[28px] sm:text-[36px] font-extrabold text-[#1d1d1f] tracking-tight text-center mb-4">
            One platform. Every channel.
          </h2>
          <p className="text-[17px] text-[#6e6e73] text-center max-w-[520px] mx-auto mb-14">
            Manage all your marketing campaigns from a single dashboard. Email, SMS, social, ads, and listings, all coordinated and reported together.
          </p>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {channelCards.map((c) => (
              <div key={c.title} className="bg-[#f5f5f7] rounded-[20px] border border-[#e5e5ea] p-7 flex flex-col gap-4">
                <div className="w-12 h-12 rounded-[10px] bg-[#e8f7fb] flex items-center justify-center">
                  <Image
                    src={c.img}
                    alt={c.title}
                    width={28}
                    height={28}
                    className="w-7 h-7 object-contain"
                  />
                </div>
                <h3 className="text-[17px] font-extrabold text-[#1d1d1f]">{c.title}</h3>
                <p className="text-[14px] text-[#6e6e73] leading-relaxed">{c.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURE ROWS */}
      <section className="py-4 border-b border-[#e5e5ea]">
        {features.map((f, idx) => (
          <div
            key={f.id}
            id={f.id}
            className={`max-w-[1200px] mx-auto px-6 py-16 flex flex-col ${f.imgLeft ? "lg:flex-row-reverse" : "lg:flex-row"} gap-12 lg:gap-20 items-center ${idx < features.length - 1 ? "border-b border-[#e5e5ea]" : ""}`}
          >
            <div className="flex-1 min-w-0">
              <h2 className="text-[26px] sm:text-[34px] font-extrabold text-[#1d1d1f] tracking-tight mb-5 leading-tight" style={{ textWrap: "balance" }}>
                {f.h2}
              </h2>
              {f.body.split("\n\n").map((para, i) => (
                <p key={i} className="text-[16px] text-[#6e6e73] leading-relaxed mb-4">{para}</p>
              ))}
              <Link
                href={f.cta.href}
                className="inline-flex items-center gap-1 text-[#18b5d8] font-semibold text-[15px] hover:underline mt-2"
              >
                {f.cta.label}
                <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4">
                  <path fillRule="evenodd" d="M3 10a.75.75 0 01.75-.75h10.638L10.23 5.29a.75.75 0 111.04-1.08l5.5 5.25a.75.75 0 010 1.08l-5.5 5.25a.75.75 0 11-1.04-1.08l4.158-3.96H3.75A.75.75 0 013 10z" clipRule="evenodd" />
                </svg>
              </Link>
            </div>
            <div className="flex-1 min-w-0 w-full">
              <div className="relative rounded-[20px] overflow-hidden shadow-lg">
                <Image
                  src={f.img}
                  alt={f.alt}
                  width={f.width}
                  height={f.height}
                  className="w-full h-auto"
                  sizes="(max-width: 1024px) 100vw, 50vw"
                />
              </div>
            </div>
          </div>
        ))}
      </section>

      {/* READYMADE EMAIL */}
      <section className="py-20 px-6 bg-[#f5f5f7] border-b border-[#e5e5ea]">
        <div className="max-w-[1200px] mx-auto flex flex-col lg:flex-row items-center gap-12 lg:gap-16">
          <div className="flex-1 min-w-0">
            <h2 className="text-[26px] sm:text-[34px] font-extrabold text-[#1d1d1f] tracking-tight mb-5 leading-tight" style={{ textWrap: "balance" }}>
              Ready-made campaigns built for local businesses
            </h2>
            <p className="text-[16px] text-[#6e6e73] leading-relaxed mb-4">
              Don't start from scratch. Our campaign library includes pre-built email and SMS sequences for the most common local business use cases, welcome sequences, appointment reminders, review requests, re-engagement flows, seasonal promotions, and more.
            </p>
            <p className="text-[16px] text-[#6e6e73] leading-relaxed mb-6">
              Choose a template, customize the copy and branding, set your triggers, and launch. Most campaigns go live in under an hour.
            </p>
            <Link
              href="/contact"
              className="inline-flex items-center justify-center bg-[#18b5d8] hover:bg-[#14a2c2] text-white font-bold text-[15px] px-8 py-4 rounded-full transition-colors duration-150"
            >
              Get started today
            </Link>
          </div>
          <div className="flex-1 min-w-0 w-full">
            <div className="relative rounded-[20px] overflow-hidden shadow-lg">
              <Image
                src={CDN + "2025/05/readymade-email.webp"}
                alt="Ready-made email campaign templates for local businesses showing customizable layouts"
                width={600}
                height={400}
                className="w-full h-auto"
                sizes="(max-width: 1024px) 100vw, 50vw"
              />
            </div>
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section className="py-20 px-6 border-b border-[#e5e5ea]">
        <div className="max-w-[1200px] mx-auto">
          <h2 className="text-[28px] sm:text-[36px] font-extrabold text-[#1d1d1f] tracking-tight text-center mb-14">
            What our clients say about campaign results
          </h2>
          <div className="grid sm:grid-cols-3 gap-6">
            {testimonials.map((t) => (
              <div
                key={t.name}
                className="bg-[#f5f5f7] rounded-[20px] border border-[#e5e5ea] p-8 flex flex-col gap-5"
              >
                <svg viewBox="0 0 32 24" className="w-8 h-6 text-[#18b5d8] flex-shrink-0" fill="currentColor">
                  <path d="M0 24V14.4C0 6.4 4.8 1.6 14.4 0l1.6 2.4C10.4 3.6 7.6 6 6.4 9.6H12V24H0zm20 0V14.4C20 6.4 24.8 1.6 34.4 0L36 2.4C30.4 3.6 27.6 6 26.4 9.6H32V24H20z" />
                </svg>
                <p className="text-[15px] text-[#1d1d1f] leading-relaxed flex-1 italic">{t.quote}</p>
                <div>
                  <p className="text-[14px] font-bold text-[#1d1d1f]">{t.name}</p>
                  <p className="text-[13px] text-[#86868b]">{t.company}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#07141a] py-24 px-6 relative overflow-hidden">
        <div
          className="absolute inset-0 pointer-events-none opacity-[0.07]"
          style={{ backgroundImage: "radial-gradient(circle at 65% 45%, #18b5d8 0%, transparent 55%)" }}
        />
        <div className="max-w-[760px] mx-auto text-center relative">
          <h2
            className="text-[32px] sm:text-[46px] font-extrabold text-white leading-[1.1] tracking-tight mb-5"
            style={{ textWrap: "balance" }}
          >
            Start turning your customer list into revenue
          </h2>
          <p className="text-[#8d9aab] text-[17px] leading-relaxed max-w-[500px] mx-auto mb-10">
            Most local businesses are sitting on a goldmine of past customers and unconverted leads. A 30-minute call is enough to map out a campaign strategy for your specific business.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/contact"
              className="inline-flex items-center justify-center bg-[#18b5d8] hover:bg-[#14a2c2] text-white font-bold text-[16px] px-10 py-5 rounded-full transition-colors duration-150"
            >
              Book a free strategy call
            </Link>
            <Link
              href="/plans"
              className="inline-flex items-center justify-center bg-white/10 hover:bg-white/20 text-white font-semibold text-[16px] px-10 py-5 rounded-full transition-colors duration-150"
            >
              View pricing
            </Link>
          </div>
        </div>
      </section>

    </div>
  );
}
