import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "FAQ | AI Visibility, GEO & Local SEO Questions | Shark AI Solutions",
  description:
    "Get answers to the most common questions about AI search visibility, Generative Engine Optimization, local SEO, and how Shark AI Solutions helps your business get recommended by ChatGPT, Gemini, and Google.",
  alternates: {
    canonical: "https://shark-ai-solutions.com/faq",
  },
  openGraph: {
    title: "FAQ | Shark AI Solutions",
    description:
      "Common questions about AI visibility, GEO, local SEO, AI employees, and what it's like to work with Shark AI Solutions.",
    url: "https://shark-ai-solutions.com/faq",
  },
};

type Question = { q: string; a: string[] };
type Category = { id: string; label: string; questions: Question[] };

const categories: Category[] = [
  {
    id: "ai-search",
    label: "AI Search & Visibility",
    questions: [
      {
        q: "What is Generative Engine Optimization (GEO)?",
        a: [
          "Generative Engine Optimization (GEO) is the practice of optimizing your business so that AI-powered platforms, including ChatGPT, Gemini, Google AI Overviews, Claude, and Perplexity, recommend you by name when people ask questions in your category.",
          "Unlike traditional SEO, which targets ranked blue links, GEO targets the AI-generated answers that now appear before any results and receive the majority of user attention. GEO involves optimizing your website's entity signals, content structure, schema markup, and citation profile so that AI models recognize your business as a trustworthy, authoritative answer to relevant queries.",
        ],
      },
      {
        q: "How does ChatGPT find and recommend my business?",
        a: [
          "ChatGPT and other large language models learn about businesses from publicly available data: your website, Google Business Profile, structured schema markup, third-party directories, review platforms, news mentions, and citations distributed across the web.",
          "When someone asks ChatGPT 'Who is the best [your service] near [your city]?', the model retrieves businesses it has encountered most consistently in credible, structured sources. If your information is fragmented, inconsistent, or missing from key sources, ChatGPT may not know you exist, or may describe you inaccurately. Appearing in AI answers requires building a consistent, authoritative presence that makes your business a reliable data source for these models.",
        ],
      },
      {
        q: "What is AI visibility, and why does it matter?",
        a: [
          "AI visibility is the degree to which your business appears in responses generated by AI-powered platforms, including ChatGPT, Google AI Overviews, Gemini, Claude, and Perplexity. A business with high AI visibility is consistently cited, named, or recommended by AI tools when prospective customers ask category-relevant questions.",
          "AI visibility is increasingly important because AI-generated answers are now the first thing many users see when searching, often appearing above traditional search results and receiving more engagement and trust than a list of links.",
        ],
      },
      {
        q: "How is GEO different from traditional SEO?",
        a: [
          "Traditional SEO is about appearing in ranked lists of links, where algorithms like Google's PageRank evaluate factors like backlinks, keyword usage, and page authority. GEO is about being cited as an authoritative answer by AI models, which evaluate signals like entity consistency, structured data, content depth, citation breadth, and how clearly your expertise is communicated across the web.",
          "The two disciplines overlap, but GEO requires additional work: FAQ schema, entity optimization, and ensuring your business data appears consistently in the sources AI models rely on, which often includes directories, databases, and structured citations that traditional SEO doesn't prioritize.",
        ],
      },
      {
        q: "If I rank on Google, will I automatically show up in AI answers?",
        a: [
          "Not necessarily. Google rankings and AI citation are increasingly separate. A business can rank on the first page of Google results and still be absent from AI-generated answers, because AI models pull from a much wider range of sources than Google's ranking index.",
          "They include structured data, knowledge graphs, business directories, review platforms, and citation databases. Conversely, some businesses that rank lower in traditional search consistently appear in AI recommendations because their entity data is clean, structured, and widely distributed. AI visibility requires its own intentional strategy.",
        ],
      },
      {
        q: "Which AI platforms should my business be visible on?",
        a: [
          "The most impactful AI platforms for local and regional businesses are ChatGPT, Google AI Overviews, Gemini, Perplexity, and Claude. Each uses a different underlying model and citation methodology, but they all reward the same core signals: consistent business information, strong review profiles, structured schema markup, topical authority through content, and citations from credible third-party sources.",
          "We monitor your visibility across all major AI platforms and optimize your digital footprint to appear on each one.",
        ],
      },
      {
        q: "How long does it take to appear in AI answers?",
        a: [
          "AI visibility improvements typically appear within 60 to 120 days of implementing a structured GEO strategy. The timeline depends on how much cleanup is required in your current citation profile, how established your website's authority is, and how competitive your local market is.",
          "Some clients see AI mentions appear within 30 days after fixing critical gaps like missing schema markup or inconsistent NAP data. Full AI authority, where your business is consistently cited across all major platforms, typically develops over four to six months of sustained effort.",
        ],
      },
    ],
  },
  {
    id: "local-seo",
    label: "Local SEO",
    questions: [
      {
        q: "What is local SEO, and why does my business need it?",
        a: [
          "Local SEO is the practice of optimizing your online presence so your business appears when people nearby search for the products or services you offer. It covers your Google Business Profile, local directory listings, NAP citation consistency, geolocation rank tracking, and customer review management.",
          "For businesses that rely on foot traffic or serve a defined service area, local SEO is one of the highest-ROI investments available because it captures people at the exact moment they're looking to buy.",
        ],
      },
      {
        q: "Why does NAP consistency matter so much?",
        a: [
          "NAP stands for Name, Address, and Phone number. Search engines and AI models treat your NAP data as the authoritative identity of your business. When your information is inconsistent across directories, your website, and data aggregators, search algorithms become uncertain about which version is correct.",
          "That uncertainty leads to lower local rankings and, increasingly, to being omitted from AI-generated recommendations. Consistent NAP data builds trust with both search engines and the customers who rely on that information to contact you.",
        ],
      },
      {
        q: "What is a geolocation rank tracking grid?",
        a: [
          "A geolocation rank tracking grid is a map of your service area divided into dozens of data points, each showing where your business ranks in Google Maps results from that specific location. Rather than showing a single average ranking, the grid reveals exactly where you're dominating the map pack, where you're buried on page two, and where you're invisible.",
          "This hyperlocal view lets us identify which neighborhoods to target with additional content, citations, and profile optimization, so your budget goes toward the gaps that matter most.",
        ],
      },
      {
        q: "How long does local SEO take to work?",
        a: [
          "Most businesses see measurable improvements in map pack visibility and call volume within 60 to 90 days of starting a local SEO campaign. Listing cleanup and NAP correction often produce results within the first 30 days.",
          "Sustained ranking improvements, particularly in competitive markets, typically develop over three to six months. We track progress monthly and provide transparent reporting so you always know what's moving and why.",
        ],
      },
      {
        q: "What's the difference between ranking on Google Maps and appearing in AI answers?",
        a: [
          "Google Maps rankings are driven by Google's local algorithm, which evaluates proximity, relevance, and prominence based on your Business Profile, reviews, and website authority. AI answers are generated by language models that pull from a much wider data pool: directories, databases, structured markup, and the open web.",
          "The two can diverge significantly. A business at the top of the map pack may not appear in ChatGPT responses, while a business with strong entity signals and citation coverage may be cited by AI tools even with a modest Google Maps ranking. A comprehensive local strategy addresses both.",
        ],
      },
    ],
  },
  {
    id: "ai-employees",
    label: "AI Employees",
    questions: [
      {
        q: "What is an AI employee?",
        a: [
          "An AI employee is an AI-powered tool that handles specific business functions, such as answering phone calls, qualifying leads, booking appointments, or following up with prospects, without requiring a human to be available at that moment.",
          "Unlike basic chatbots that respond to scripted inputs, AI employees use large language models to hold natural conversations, understand context, and route or respond appropriately. They work around the clock, don't call in sick, and scale with your business without adding payroll.",
        ],
      },
      {
        q: "Can an AI employee replace my front desk or receptionist?",
        a: [
          "An AI employee can handle the most time-consuming parts of a receptionist's role: answering inbound calls, collecting caller information, answering common questions, and routing calls or booking appointments.",
          "We don't position AI employees as replacements for people. Rather, they handle volume so your team can focus on tasks that require human judgment and relationship-building. For most small to mid-size businesses, this means fewer missed calls, faster response times, and a better first impression for customers who reach out after hours.",
        ],
      },
      {
        q: "How does the AI voice receptionist handle after-hours calls?",
        a: [
          "The AI voice receptionist is always on. When a call comes in after your office closes, it answers in a natural, conversational tone using your business's name and information. It can answer questions about your services, hours, and pricing, collect contact details and the reason for the call, and either schedule an appointment or create a follow-up task for your team.",
          "Transcripts and recordings are available in your dashboard so nothing falls through the cracks.",
        ],
      },
      {
        q: "What industries benefit most from AI employees?",
        a: [
          "AI employees deliver the highest ROI in businesses that receive high call volume but can't always answer promptly: home services (HVAC, plumbing, roofing), healthcare and medical practices, legal offices, real estate, and automotive services. Essentially, any business where a missed call is a missed sale is a strong candidate.",
          "We've built industry-specific AI employees for healthcare, legal, home services, contractors, and real estate, each trained on common terminology and scenarios in those industries.",
        ],
      },
    ],
  },
  {
    id: "working-with-us",
    label: "Working With Shark AI Solutions",
    questions: [
      {
        q: "Where do you serve clients?",
        a: [
          "Our primary service area is the Tampa Bay region, including Wesley Chapel, Tampa, Lutz, Land O' Lakes, New Port Richey, and surrounding communities. We also work with franchise organizations, multi-location businesses, and national clients remotely.",
          "Our local SEO and AI visibility services are effective for businesses in any market, and we have active clients across multiple states.",
        ],
      },
      {
        q: "What makes Shark AI Solutions different from a traditional marketing agency?",
        a: [
          "We focus exclusively on AI visibility and branded digital presence, not on running ads or managing social media calendars. Traditional agencies optimize for clicks and impressions. We optimize for citations, entity authority, and AI model recognition, the signals that determine whether your business appears when customers ask ChatGPT or Google AI Overviews for a recommendation.",
          "We also build and deploy AI employees that reduce labor costs and improve response times, which most agencies don't offer at all.",
        ],
      },
      {
        q: "Do I need to sign a long-term contract?",
        a: [
          "We offer both month-to-month engagements and longer-term plans, depending on the service. AI visibility and local SEO campaigns produce compounding results over time, so clients who commit to six months or more see substantially better outcomes than those who treat it as a one-time effort.",
          "We'll recommend the structure that makes the most sense for your goals and budget during your initial strategy call.",
        ],
      },
      {
        q: "How quickly can we get started?",
        a: [
          "Once you book a strategy call and we agree on scope, most campaigns launch within five to seven business days. For AI employees, setup typically takes three to five business days.",
          "We'll send a checklist of what we need from you, such as access to your Google Business Profile, website credentials, and brand materials, to make onboarding as fast as possible.",
        ],
      },
      {
        q: "What's included in the free Snapshot Report?",
        a: [
          "The free Snapshot Report gives you a scored overview of your business's digital presence across five key areas: reviews, listings accuracy, social activity, website health, and local SEO. It shows exactly where you stand today, where you're losing ground to competitors, and which issues to fix first for the fastest impact.",
          "It takes about 60 seconds to generate and no payment is required.",
        ],
      },
    ],
  },
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: categories.flatMap((c) =>
    c.questions.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: {
        "@type": "Answer",
        text: a.join("\n\n"),
      },
    }))
  ),
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: "https://shark-ai-solutions.com" },
    { "@type": "ListItem", position: 2, name: "FAQ", item: "https://shark-ai-solutions.com/faq" },
  ],
};

const sectionBg: Record<number, string> = {
  0: "bg-white",
  1: "bg-[#f5f5f7]",
  2: "bg-white",
  3: "bg-[#f5f5f7]",
};

export default function FaqPage() {
  return (
    <div className="bg-white">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      {/* HERO */}
      <section className="bg-[#07141a] py-20 px-6">
        <div className="max-w-[800px] mx-auto pt-8 text-center">
          <span className="inline-block text-[#18b5d8] text-[13px] font-bold tracking-[2px] uppercase mb-5">
            FAQ
          </span>
          <h1
            className="text-[38px] sm:text-[52px] font-extrabold text-white leading-[1.08] tracking-tight mb-6"
            style={{ textWrap: "balance" }}
          >
            Questions about AI visibility, local SEO, and what we do
          </h1>
          <p className="text-[#8d9aab] text-[18px] leading-relaxed max-w-[580px] mx-auto">
            Answers to the questions we hear most often, from how ChatGPT finds businesses to what GEO actually means and how we work with clients.
          </p>
        </div>
      </section>

      {/* CATEGORY JUMP NAV */}
      <nav className="sticky top-0 z-20 bg-white border-b border-[#e5e5ea] shadow-sm">
        <div className="max-w-[800px] mx-auto px-6 py-0 flex gap-1 overflow-x-auto scrollbar-hide">
          {categories.map((c) => (
            <a
              key={c.id}
              href={`#${c.id}`}
              className="shrink-0 text-[13px] font-semibold text-[#6e6e73] hover:text-[#18b5d8] py-4 px-3 border-b-2 border-transparent hover:border-[#18b5d8] transition-colors duration-150 whitespace-nowrap"
            >
              {c.label}
            </a>
          ))}
        </div>
      </nav>

      {/* FAQ SECTIONS */}
      {categories.map((cat, catIdx) => (
        <section
          key={cat.id}
          id={cat.id}
          className={`${sectionBg[catIdx]} border-b border-[#e5e5ea] py-16 px-6 scroll-mt-14`}
        >
          <div className="max-w-[800px] mx-auto">
            <h2 className="text-[22px] font-extrabold text-[#1d1d1f] tracking-tight mb-8 pb-4 border-b border-[#e5e5ea]">
              {cat.label}
            </h2>

            <div>
              {cat.questions.map((item, idx) => (
                <details
                  key={idx}
                  className={`group ${idx < cat.questions.length - 1 ? "border-b border-[#e5e5ea]" : ""}`}
                >
                  <summary className="flex items-start justify-between gap-6 py-5 cursor-pointer select-none list-none [&::-webkit-details-marker]:hidden">
                    <span className="font-semibold text-[17px] text-[#1d1d1f] leading-snug">
                      {item.q}
                    </span>
                    <svg
                      viewBox="0 0 20 20"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      className="shrink-0 w-5 h-5 mt-0.5 text-[#18b5d8] transition-transform duration-200 group-open:rotate-180"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 8l5 5 5-5" />
                    </svg>
                  </summary>
                  <div className="pb-6 space-y-3">
                    {item.a.map((para, i) => (
                      <p key={i} className="text-[15px] text-[#6e6e73] leading-relaxed max-w-[680px]">
                        {para}
                      </p>
                    ))}
                  </div>
                </details>
              ))}
            </div>
          </div>
        </section>
      ))}

      {/* CTA */}
      <section className="bg-[#07141a] py-24 px-6">
        <div className="max-w-[680px] mx-auto text-center">
          <h2
            className="text-[28px] sm:text-[38px] font-extrabold text-white tracking-tight mb-5 leading-tight"
            style={{ textWrap: "balance" }}
          >
            Still have questions? Let's talk.
          </h2>
          <p className="text-[#8d9aab] text-[17px] leading-relaxed mb-10 max-w-[520px] mx-auto">
            Book a free strategy call and we'll walk through your current visibility, what your competitors are doing, and exactly what we'd recommend for your market.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/contact"
              className="inline-flex items-center justify-center bg-[#18b5d8] hover:bg-[#14a2c2] text-white font-bold text-[15px] px-8 py-4 rounded-full transition-colors duration-150"
            >
              Book a strategy call
            </Link>
            <Link
              href="/free-report"
              className="inline-flex items-center justify-center bg-white/10 hover:bg-white/20 text-white font-semibold text-[15px] px-8 py-4 rounded-full transition-colors duration-150"
            >
              Get a free Snapshot Report
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
