import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'AI Customer Acquisition Statistics 2026 | Shark AI Solutions',
  description: '91% of SMBs using AI report revenue gains. 83% zero-click rate when AI Overviews appear. The sourced statistics behind the AI customer acquisition shift.',
  alternates: { canonical: 'https://sharkbrandingsolutions.com/resources/ai-customer-acquisition-statistics-2026' },
  openGraph: {
    title: 'AI Customer Acquisition Statistics You Need to Know in 2026',
    description: 'The numbers behind the AI customer acquisition shift, market size, lead generation, AI search, ROI, and small business adoption. Sourced from Salesforce, BCG, Gartner, HubSpot, and 10+ more.',
    url: 'https://sharkbrandingsolutions.com/resources/ai-customer-acquisition-statistics-2026',
    type: 'article',
  },
}

const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'BlogPosting',
  headline: 'AI Customer Acquisition Statistics You Need to Know in 2026',
  description: 'Sourced statistics on AI customer acquisition: market size, lead generation ROI, AI search behavior, small business adoption, and 2027–2030 projections. 14+ primary sources.',
  url: 'https://sharkbrandingsolutions.com/resources/ai-customer-acquisition-statistics-2026',
  datePublished: '2026-06-14',
  dateModified: '2026-06-14',
  author: {
    '@type': 'Person',
    '@id': 'https://sharkbrandingsolutions.com/about#michelle',
    name: 'Michelle Stanaland',
    url: 'https://sharkbrandingsolutions.com/about#michelle',
    jobTitle: 'Managing Partner and Founder, Shark AI Solutions',
  },
  publisher: {
    '@id': 'https://sharkbrandingsolutions.com/#organization',
  },
  mainEntityOfPage: {
    '@type': 'WebPage',
    '@id': 'https://sharkbrandingsolutions.com/resources/ai-customer-acquisition-statistics-2026',
  },
  keywords: ['AI customer acquisition', 'AI marketing statistics 2026', 'AI lead generation', 'Google AI Overviews statistics', 'small business AI adoption', 'AI visibility'],
  articleSection: 'Research & Data',
}

const faqs = [
  {
    q: 'What is AI customer acquisition?',
    a: 'AI customer acquisition is the use of artificial intelligence tools, including AI search platforms like ChatGPT and Google AI Overviews, AI lead generation agents, and AI-powered marketing automation, to attract, qualify, and convert new customers. It differs from traditional digital marketing in that buyers increasingly discover and evaluate businesses through AI recommendations rather than traditional search results or paid ads.',
  },
  {
    q: 'How much does AI reduce customer acquisition costs?',
    a: 'Businesses using AI for customer acquisition report an average 32% reduction in customer acquisition costs compared to traditional methods, with mature personalization implementations achieving up to 50% CAC reduction. B2B companies see an average $2.40 reduction per qualified lead, and AI-driven strategies deliver 52% better customer acquisition costs overall versus traditional approaches.',
  },
  {
    q: 'What is AI visibility and why does it matter for local businesses?',
    a: 'AI visibility is how prominently your business appears when AI tools like ChatGPT, Google AI Overviews, and Gemini answer questions relevant to your services. When a potential customer asks "best HVAC company near me" or "who does roof repair in Wesley Chapel," AI visibility determines whether your business is recommended. With 83% zero-click rates when AI Overviews appear and 94% of B2B buyers using AI during purchasing, being invisible to AI search means losing customers before they ever reach your website.',
  },
  {
    q: 'What percentage of B2B buyers use AI during the purchase process?',
    a: '94% of B2B buyers now use generative AI during the purchase process, according to current research. Enterprise buyers increasingly arrive at vendor conversations with shortlists already generated by ChatGPT or Claude. This compresses the traditional consideration phase from weeks to hours, businesses that are not visible in AI search are being eliminated from consideration before a single human conversation happens.',
  },
  {
    q: 'Should small businesses invest in AI for marketing?',
    a: 'Yes, and the data is unambiguous. 91% of small businesses using AI report revenue increases, 80%+ report productivity improvements, and small businesses now adopt AI faster than large enterprises (reversing the 2023–2024 pattern). The risk is not in adopting AI too early; it is in waiting while competitors establish AI visibility and lead generation advantages that compound over time.',
  },
  {
    q: 'What is the ROI timeline for AI lead generation?',
    a: 'B2B companies implementing AI lead generation see a 73% increase in qualified leads within 6 months and a 4.2x ROI after 18 months. The average ROI across AI marketing implementations is 300%. Results are faster for businesses starting from a strong local presence, Google Business Profile completeness, review volume, and NAP consistency all accelerate how quickly AI search platforms begin recommending the business.',
  },
  {
    q: 'How does Google AI Overviews affect local business discovery?',
    a: 'Google AI Overviews now appear on 18% of commercial queries (up from 8% in early 2025) and trigger an 83% zero-click rate, meaning 83% of searchers who see an AI Overview do not click any organic results. For local businesses, this means that appearing in an AI Overview is now more valuable than ranking #1 in traditional search results. Businesses cited in AI Overviews capture the attention without the click; those not cited are effectively invisible for those queries.',
  },
]

const roiTable = [
  { metric: 'Campaign ROI', improvement: '+22%' },
  { metric: 'Conversion Rate', improvement: '+32%' },
  { metric: 'Customer Acquisition Cost', improvement: '−29%' },
  { metric: 'Email Open Rates', improvement: '+27%' },
  { metric: 'Paid Ad Conversion', improvement: '+33%' },
  { metric: 'Revenue', improvement: '+41%' },
]

export default function AiCustomerAcquisitionStatsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: faqs.map((f) => ({
              '@type': 'Question',
              name: f.q,
              acceptedAnswer: { '@type': 'Answer', text: f.a },
            })),
          }),
        }}
      />

      {/* Hero */}
      <section className="bg-white pt-24 pb-16 px-6 border-b border-[#e8e8ed]">
        <div className="max-w-[720px] mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <Link href="/resources" className="text-[13px] text-[#18b5d8] font-semibold hover:underline">
              ← Resources
            </Link>
            <span className="text-[#e0e0e0]">/</span>
            <span className="text-[13px] text-[#999]">Research &amp; Data</span>
          </div>
          <p className="text-[#18b5d8] text-[13px] font-semibold tracking-[0.2em] uppercase mb-5">Research · June 2026</p>
          <h1 className="display-hero text-[#0a0a0a] mb-6" style={{ textWrap: 'balance' }}>
            AI Customer Acquisition Statistics You Need to Know in 2026
          </h1>
          <p className="lead-airy text-[#555] mb-8" style={{ textWrap: 'balance' }}>
            The numbers behind the AI customer acquisition shift, market size, lead generation ROI, AI search behavior, and small business adoption. Sourced from Salesforce, BCG, Gartner, HubSpot, and 10+ primary research organizations.
          </p>
          <div className="flex items-center gap-3 text-[13px] text-[#999]">
            <span>By Michelle Stanaland</span>
            <span>·</span>
            <span>June 14, 2026</span>
            <span>·</span>
            <span>10 min read</span>
          </div>
        </div>
      </section>

      {/* Article body */}
      <section className="bg-white px-6 py-16">
        <div className="max-w-[720px] mx-auto">

          {/* Key stats at a glance */}
          <div className="mb-16">
            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-6">Key stats at a glance</h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
              {[
                { stat: '73%', label: 'more qualified B2B leads with AI (Salesforce)' },
                { stat: '$47B', label: 'AI marketing market size in 2026' },
                { stat: '83%', label: 'zero-click rate when AI Overviews appear' },
                { stat: '91%', label: 'of SMBs using AI report revenue gains' },
              ].map((item) => (
                <div key={item.stat} className="bg-[#f5f5f7] rounded-[16px] p-5 text-center border border-[#e8e8ed]">
                  <p className="text-[32px] font-extrabold text-[#18b5d8] leading-none mb-2">{item.stat}</p>
                  <p className="text-[12px] text-[#555] leading-snug">{item.label}</p>
                </div>
              ))}
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
              {[
                { stat: '88%', label: 'of marketers use AI in daily tasks' },
                { stat: '32%', label: 'average reduction in CAC' },
                { stat: '41%', label: 'average revenue increase with AI marketing' },
              ].map((item) => (
                <div key={item.stat} className="bg-[#f5f5f7] rounded-[16px] p-5 text-center border border-[#e8e8ed]">
                  <p className="text-[32px] font-extrabold text-[#18b5d8] leading-none mb-2">{item.stat}</p>
                  <p className="text-[12px] text-[#555] leading-snug">{item.label}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Market size */}
          <div className="mb-16">
            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-4">Market size &amp; growth</h2>
            <div className="text-[17px] leading-[1.75] text-[#333] space-y-4 mb-8">
              <p>
                The AI marketing industry reached <strong>$47.32 billion in 2026</strong>, up from $24 billion in 2025, nearly doubling in a single year. Analysts project the market to reach <strong>$215.03 billion by 2035</strong> at a 24.5% compound annual growth rate, making it one of the fastest-growing segments in enterprise software.
              </p>
              <p>
                Generative AI adoption in marketing workflows surged <strong>116% year-over-year</strong> from 2024 to 2026. The share of marketers using generative AI in recurring workflows grew from 51% in Q1 2024 to <strong>87% by Q1 2026</strong>, a 70% increase in just two years.
              </p>
            </div>
            <div className="bg-[#f5f5f7] rounded-[16px] border border-[#e8e8ed] overflow-hidden">
              <div className="px-6 py-4 border-b border-[#e8e8ed] bg-white">
                <p className="text-[11px] font-bold uppercase tracking-[0.15em] text-[#999]">Market milestones</p>
              </div>
              {[
                { label: 'AI marketing market (2026)', value: '$47.32B' },
                { label: 'Marketing automation software (2026)', value: '$8.14B' },
                { label: 'Projected AI marketing market (2035)', value: '$215.03B' },
                { label: 'CAGR through 2035', value: '24.5%' },
                { label: 'Gen AI adoption in workflows (Q1 2026)', value: '87%' },
                { label: 'YoY gen AI adoption growth (2024–2026)', value: '+116%' },
              ].map((row, i) => (
                <div key={row.label} className={`flex items-center justify-between px-6 py-4 border-b border-[#f0f0f0] last:border-0 ${i % 2 === 1 ? 'bg-[#fafafa]' : 'bg-white'}`}>
                  <span className="text-[14px] text-[#555]">{row.label}</span>
                  <span className="text-[15px] font-bold text-[#0a0a0a]">{row.value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Lead generation */}
          <div className="mb-16">
            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-4">AI lead generation &amp; sales</h2>
            <div className="text-[17px] leading-[1.75] text-[#333] space-y-4 mb-8">
              <p>
                B2B companies implementing AI lead generation see a <strong>73% increase in qualified leads within 6 months</strong> and a <strong>4.2x ROI after 18 months</strong> on their AI lead generation investment. Conversion rates with AI strategies are 37% higher on average, and AI-driven campaigns deliver 52% better customer acquisition costs versus traditional methods.
              </p>
              <p>
                E-commerce provides some of the clearest data: AI chat delivers <strong>4x higher conversion rates</strong> compared to non-AI interactions (12.3% vs. 3.1%), and shoppers complete purchases <strong>47% faster</strong> with AI chat assistance. Salesforce&rsquo;s Agentforce product, their AI sales agent platform, exceeded $800 million ARR in Q4 FY26, reflecting enterprise-level confidence in the category.
              </p>
            </div>
            <div className="bg-[#f5f5f7] rounded-[16px] border border-[#e8e8ed] overflow-hidden">
              <div className="px-6 py-4 border-b border-[#e8e8ed] bg-white">
                <p className="text-[11px] font-bold uppercase tracking-[0.15em] text-[#999]">Lead generation benchmarks</p>
              </div>
              {[
                { label: 'Increase in qualified B2B leads (6 months)', value: '+73%' },
                { label: 'ROI on AI lead gen investment (18 months)', value: '4.2x' },
                { label: 'Higher conversion rates vs. non-AI', value: '+37%' },
                { label: 'Better CAC vs. traditional methods', value: '52%' },
                { label: 'E-commerce AI chat conversion rate', value: '12.3%' },
                { label: 'Faster purchase completion with AI chat', value: '47%' },
                { label: 'Avg. reduction per qualified B2B lead', value: '−$2.40' },
              ].map((row, i) => (
                <div key={row.label} className={`flex items-center justify-between px-6 py-4 border-b border-[#f0f0f0] last:border-0 ${i % 2 === 1 ? 'bg-[#fafafa]' : 'bg-white'}`}>
                  <span className="text-[14px] text-[#555]">{row.label}</span>
                  <span className="text-[15px] font-bold text-[#0a0a0a]">{row.value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* AI search */}
          <div className="mb-16">
            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-4">AI search &amp; buyer discovery</h2>
            <div className="text-[17px] leading-[1.75] text-[#333] space-y-4 mb-8">
              <p>
                The scale of AI search platforms is no longer a future projection, it is the current reality. ChatGPT reached <strong>900 million weekly active users</strong> in February 2026 (up 125% year-over-year) and surpassed Bing with <strong>5.4 billion global monthly visits</strong> versus Bing&rsquo;s 1.9 billion. Google AI Overviews reach <strong>2 billion monthly users</strong> across more than 200 countries.
              </p>
              <p>
                The buyer behavior shift is equally significant. <strong>94% of B2B buyers</strong> now use generative AI during the purchase process. Enterprise buyers arrive at vendor conversations with shortlists already generated by ChatGPT or Claude. <strong>24% of consumers</strong> are now comfortable with AI agents making purchases on their behalf, rising to <strong>32% among Gen Z</strong>.
              </p>
            </div>

            {/* Zero-click callout */}
            <div className="bg-[#0a0a0a] rounded-[20px] p-8 mb-8">
              <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#18b5d8] mb-3">Zero-Click Reality</p>
              <p className="text-[28px] font-extrabold text-white leading-tight mb-3">83% zero-click rate when AI Overviews appear.</p>
              <p className="text-[15px] text-white/60 leading-relaxed">
                58.5% of all U.S. searches now end without any external click. When Google AI Overviews appear, that rate rises to 83%. Businesses cited in AI Overviews win the customer&rsquo;s attention without the click. Businesses not cited are invisible for those queries, regardless of where they rank in traditional search.
              </p>
            </div>

            <div className="bg-[#f5f5f7] rounded-[16px] border border-[#e8e8ed] overflow-hidden">
              <div className="px-6 py-4 border-b border-[#e8e8ed] bg-white">
                <p className="text-[11px] font-bold uppercase tracking-[0.15em] text-[#999]">AI search platform scale</p>
              </div>
              {[
                { label: 'ChatGPT weekly active users (Feb 2026)', value: '900M' },
                { label: 'ChatGPT global monthly visits', value: '5.4B' },
                { label: 'Google AI Overviews monthly users', value: '2B' },
                { label: 'AI Overviews on commercial queries', value: '18%' },
                { label: 'B2B buyers using AI during purchase', value: '94%' },
                { label: 'U.S. searches ending without a click', value: '58.5%' },
                { label: 'Zero-click rate when AI Overview appears', value: '83%' },
              ].map((row, i) => (
                <div key={row.label} className={`flex items-center justify-between px-6 py-4 border-b border-[#f0f0f0] last:border-0 ${i % 2 === 1 ? 'bg-[#fafafa]' : 'bg-white'}`}>
                  <span className="text-[14px] text-[#555]">{row.label}</span>
                  <span className="text-[15px] font-bold text-[#0a0a0a]">{row.value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* ROI */}
          <div className="mb-16">
            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-4">ROI &amp; performance</h2>
            <div className="text-[17px] leading-[1.75] text-[#333] space-y-4 mb-8">
              <p>
                The average ROI across AI marketing implementations is <strong>300%</strong>. AI personalization drives <strong>31% of e-commerce revenues</strong> for brands that have fully implemented it, and businesses with mature personalization achieve <strong>up to 50% reduction in customer acquisition costs</strong>.
              </p>
              <p>
                71% of consumers now expect personalized interactions, and 80% are more likely to purchase when those expectations are met. The gap between personalized and non-personalized experiences is no longer a nice-to-have; it is a conversion variable that compounds every time a buyer interacts with your business online.
              </p>
            </div>
            <div className="rounded-[16px] overflow-hidden border border-[#e8e8ed]">
              <div className="grid grid-cols-2 bg-[#f5f5f7] border-b border-[#e8e8ed] px-6 py-4">
                <span className="text-[11px] font-bold uppercase tracking-[0.15em] text-[#999]">Metric</span>
                <span className="text-[11px] font-bold uppercase tracking-[0.15em] text-[#18b5d8]">Avg. Improvement</span>
              </div>
              {roiTable.map((row, i) => (
                <div key={row.metric} className={`grid grid-cols-2 px-6 py-4 border-b border-[#f0f0f0] last:border-0 ${i % 2 === 1 ? 'bg-[#fafafa]' : 'bg-white'}`}>
                  <span className="text-[14px] text-[#555]">{row.metric}</span>
                  <span className={`text-[15px] font-bold ${row.improvement.startsWith('−') ? 'text-[#0a0a0a]' : 'text-[#18b5d8]'}`}>{row.improvement}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Small business */}
          <div className="mb-16">
            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-4">Small business AI adoption</h2>
            <div className="text-[17px] leading-[1.75] text-[#333] space-y-4 mb-8">
              <p>
                <strong>68% of U.S. small businesses</strong> now use AI regularly, with 58% using generative AI specifically (up from 40% in 2025). Among those businesses, <strong>91% report revenue increases</strong> and more than 80% report measurable productivity improvements.
              </p>
              <p>
                The most significant trend in the data: by mid-2025, small businesses began adopting AI <em>faster</em> than large enterprises, reversing the 2023–2024 pattern where enterprise adoption led. Among companies with 10 to 100 employees, AI adoption jumped from 47% to 68% in a single year. Small businesses that adopt early are <strong>1.8x more likely to report competitive advantage</strong> versus larger firms in their category.
              </p>
              <p>
                The primary barrier to adoption remains perception: 77% of non-adopting small businesses cite no applicable use case as the reason they have not started. This barrier is directly contradicted by the 91% revenue improvement rate among those who have adopted.
              </p>
            </div>
            <div className="bg-[#f5f5f7] rounded-[16px] border border-[#e8e8ed] overflow-hidden">
              <div className="px-6 py-4 border-b border-[#e8e8ed] bg-white">
                <p className="text-[11px] font-bold uppercase tracking-[0.15em] text-[#999]">Small business adoption data</p>
              </div>
              {[
                { label: 'U.S. small businesses using AI regularly', value: '68%' },
                { label: 'Using generative AI specifically (2026)', value: '58%' },
                { label: 'SMBs using AI reporting revenue increases', value: '91%' },
                { label: 'Reporting productivity improvements', value: '80%+' },
                { label: 'Plan to adopt AI / emerging tech', value: '96%' },
                { label: 'Competitive advantage vs. larger firms', value: '1.8x' },
                { label: 'Primary adoption barrier (no use case)', value: '77%' },
              ].map((row, i) => (
                <div key={row.label} className={`flex items-center justify-between px-6 py-4 border-b border-[#f0f0f0] last:border-0 ${i % 2 === 1 ? 'bg-[#fafafa]' : 'bg-white'}`}>
                  <span className="text-[14px] text-[#555]">{row.label}</span>
                  <span className="text-[15px] font-bold text-[#0a0a0a]">{row.value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Future projections */}
          <div className="mb-16">
            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-4">Future projections (2027–2030)</h2>
            <div className="text-[17px] leading-[1.75] text-[#333] space-y-4 mb-8">
              <p>
                The next phase of AI adoption involves autonomous agents, AI systems that take actions, not just generate content. <strong>50% of enterprises will deploy autonomous AI agents by 2027</strong> (Gartner), up from 25% in 2025. By 2028, <strong>15% of day-to-day business decisions</strong> will be made autonomously by AI agents without human review.
              </p>
              <p>
                The agentic AI market, the category covering AI employees and autonomous business agents, is projected to reach <strong>$47.1 billion by 2030</strong>, with $58 billion in market disruption attributed to agentic AI by 2027 alone. For local service businesses, this means AI-powered competitors will be running 24/7 lead qualification, follow-up, and customer service workflows at scale within the next 18 months.
              </p>
            </div>
            <div className="bg-[#f5f5f7] rounded-[16px] border border-[#e8e8ed] overflow-hidden">
              <div className="px-6 py-4 border-b border-[#e8e8ed] bg-white">
                <p className="text-[11px] font-bold uppercase tracking-[0.15em] text-[#999]">2027–2030 projections</p>
              </div>
              {[
                { label: 'Enterprises deploying autonomous AI agents (2027)', value: '50%' },
                { label: 'Day-to-day decisions made by AI (2028)', value: '15%' },
                { label: 'Agentic AI market size (2030)', value: '$47.1B' },
                { label: 'Market disruption from agentic AI (2027)', value: '$58B' },
                { label: 'AI marketing industry size (2035)', value: '$215.03B' },
                { label: 'Routine business tasks automated by 2027', value: '15–50%' },
              ].map((row, i) => (
                <div key={row.label} className={`flex items-center justify-between px-6 py-4 border-b border-[#f0f0f0] last:border-0 ${i % 2 === 1 ? 'bg-[#fafafa]' : 'bg-white'}`}>
                  <span className="text-[14px] text-[#555]">{row.label}</span>
                  <span className="text-[15px] font-bold text-[#0a0a0a]">{row.value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Methodology */}
          <div className="mb-16 bg-[#f5f5f7] rounded-[16px] p-8 border border-[#e8e8ed]">
            <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#999] mb-3">Methodology &amp; sources</p>
            <p className="text-[14px] text-[#555] leading-relaxed mb-4">
              Statistics compiled from 14+ independent primary sources. Market size figures may vary across sources due to differences in market definition and scope. All data published for educational and research purposes.
            </p>
            <p className="text-[13px] text-[#999] leading-relaxed">
              Primary sources: Salesforce, BCG, Gartner, HubSpot, Deloitte, Market Research Future, MarketsandMarkets, Grand View Research, Fortune Business Insights, Statista, JP Morgan Chase Institute, U.S. Chamber of Commerce, QuickBooks, Mordor Intelligence. Compiled June 14, 2026.
            </p>
          </div>

          {/* FAQ */}
          <div className="mt-4 border-t border-[#e8e8ed] pt-12">
            <h2 className="text-[22px] font-bold text-[#0a0a0a] mb-8">Frequently asked questions</h2>
            <div className="space-y-5">
              {faqs.map((f) => (
                <details key={f.q} className="group bg-[#f5f5f7] rounded-[16px] border border-[#e8e8ed]">
                  <summary className="flex items-center justify-between px-6 py-5 cursor-pointer list-none">
                    <span className="text-[15px] font-semibold text-[#0a0a0a] pr-4">{f.q}</span>
                    <span className="text-[#18b5d8] font-bold text-[18px] shrink-0 group-open:rotate-45 transition-transform duration-150">+</span>
                  </summary>
                  <div className="px-6 pb-5 text-[14px] text-[#555] leading-relaxed">{f.a}</div>
                </details>
              ))}
            </div>
          </div>

          {/* Internal links */}
          <div className="mt-12 border-t border-[#e8e8ed] pt-10">
            <p className="text-[13px] font-bold uppercase tracking-[0.15em] text-[#999] mb-4">Related reading</p>
            <div className="space-y-3">
              <Link href="/resources/blog-how-to-appear-in-google-ai-overviews" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">How to Appear in Google AI Overviews: A 5-Signal Framework</span>
              </Link>
              <Link href="/resources/blog-end-of-local-seo-ai-visibility" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">What the End of Local SEO Means for Your Business</span>
              </Link>
              <Link href="/resources/blog-ai-funnel-chatgpt-new-front-door" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">The AI Funnel: Why ChatGPT Is the New Front Door for Your Customers</span>
              </Link>
              <Link href="/ai-visibility-consulting" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">AI Visibility Consulting, Get found by ChatGPT, Gemini, and Google AI</span>
              </Link>
            </div>
          </div>

          {/* CTA */}
          <div className="mt-12 bg-[#0a0a0a] rounded-[20px] px-8 py-10 text-center">
            <p className="text-[13px] font-semibold tracking-[0.2em] uppercase text-[#18b5d8] mb-4">Free AI Audit</p>
            <h3 className="text-[24px] font-bold text-white mb-4" style={{ textWrap: 'balance' }}>
              Find out where your business stands in AI search right now.
            </h3>
            <p className="text-white/50 text-[15px] mb-8">
              We audit your visibility across ChatGPT, Google AI Overviews, and Gemini. Delivered in 48 hours. No commitment.
            </p>
            <Link
              href="/ai-audit"
              className="inline-block bg-[#18b5d8] text-white text-[15px] font-semibold rounded-full px-8 py-4 hover:bg-[#1ec8ee] motion-safe:transition-colors duration-150"
            >
              Get My Free AI Audit
            </Link>
          </div>

        </div>
      </section>
    </>
  )
}
