import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'How Local Businesses Get Recommended in Google AI Overviews | Shark AI Solutions',
  description: 'What drives Google AI Overview recommendations for local businesses. The signals that matter, why they matter, and what separates businesses that get recommended from those that don\'t.',
  alternates: { canonical: 'https://sharkbrandingsolutions.com/resources/blog-how-to-appear-in-google-ai-overviews' },
  openGraph: {
    title: 'How Local Businesses Get Recommended in Google AI Overviews',
    description: 'The local business signals that drive Google AI Overview recommendations, and why getting them right requires more than a checklist.',
    url: 'https://sharkbrandingsolutions.com/resources/blog-how-to-appear-in-google-ai-overviews',
    type: 'article',
  },
}

const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'BlogPosting',
  headline: 'How Local Businesses Get Recommended in Google AI Overviews',
  description: 'What drives Google AI Overview recommendations for local businesses, the signals that matter, and what separates businesses that get recommended from those that don\'t.',
  url: 'https://sharkbrandingsolutions.com/resources/blog-how-to-appear-in-google-ai-overviews',
  datePublished: '2026-06-16',
  dateModified: '2026-06-16',
  author: {
    '@type': 'Person',
    '@id': 'https://sharkbrandingsolutions.com/about#josh',
    name: 'Josh Stanaland',
    url: 'https://sharkbrandingsolutions.com/about#josh',
    jobTitle: 'Partner and CTO, Shark AI Solutions',
  },
  publisher: { '@id': 'https://sharkbrandingsolutions.com/#organization' },
  mainEntityOfPage: {
    '@type': 'WebPage',
    '@id': 'https://sharkbrandingsolutions.com/resources/blog-how-to-appear-in-google-ai-overviews',
  },
  keywords: ['Google AI Overviews', 'AI search optimization', 'GEO', 'local business AI visibility', 'structured data', 'schema markup'],
  articleSection: 'AI Visibility',
}
const breadcrumbData = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://sharkbrandingsolutions.com' },
    { '@type': 'ListItem', position: 2, name: 'Resources', item: 'https://sharkbrandingsolutions.com/resources' },
    { '@type': 'ListItem', position: 3, name: structuredData.headline, item: 'https://sharkbrandingsolutions.com/resources/blog-how-to-appear-in-google-ai-overviews' },
  ],
}


const faqs = [
  {
    q: 'Do you need to rank on Google to appear in Google AI Overviews?',
    a: 'Not necessarily. Google AI Overviews draw from a broader set of signals than traditional search ranking, including structured data, Google Business Profile completeness, review volume and recency, and entity consistency across directories. A business that ranks on page 2 for a keyword can still appear in an AI Overview for a related query if its structured signals are strong. That said, pages ranking in the top 10 do have a statistical advantage, and strong traditional SEO supports AI visibility rather than working against it.',
  },
  {
    q: 'How long does it take to appear in Google AI Overviews?',
    a: 'There is no fixed timeline, but most businesses that have their core signals properly configured see movement within 30 to 90 days. Citation corrections propagate within weeks. Schema updates are processed within days of Googlebot recrawling your pages. Review volume builds over the first 60 to 90 days of a systematic review program. The AI Overview surface updates continuously, it is not a one-time indexing event.',
  },
  {
    q: 'Can a small local business appear in Google AI Overviews?',
    a: 'Yes. Local queries are one of the most active surfaces for AI Overviews. When someone asks "best HVAC company in Wesley Chapel" or "plumber near me open on Saturday," Google AI Overviews pull from local signals specifically, Google Business Profile data, review count and recency, service area, and structured data on your website. A well-optimized local business with strong GBP signals and clean schema can outperform larger national competitors in AI Overview results for local queries.',
  },
  {
    q: 'What is the difference between Google AI Overviews and ChatGPT recommendations?',
    a: 'Google AI Overviews are generated by Google\'s Gemini model and pull from Google\'s index and Google Business Profile data. They appear at the top of Google search results for certain queries. ChatGPT recommendations are generated by OpenAI\'s models and pull from a separate training corpus and real-time web browsing. The optimization signals overlap, both favor structured data, consistent citations, and authoritative content, but the specific sources differ. Appearing in one does not guarantee appearing in the other.',
  },
]

export default function HowToAppearInGoogleAiOverviewsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbData) }} />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: faqs.map((f) => ({
              '@type': 'Question',
              name: f.q,
              acceptedAnswer: { '@type': 'Answer', text: f.a },
            })),
          }),
        }}
      />

      {/* Hero */}
      <section className="bg-white pt-24 pb-16 px-6 border-b border-[#e8e8ed]">
        <div className="max-w-[720px] mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <Link href="/resources" className="text-[13px] text-[#18b5d8] font-semibold hover:underline">
              ← Resources
            </Link>
            <span className="text-[#e0e0e0]">/</span>
            <span className="text-[13px] text-[#6e6e73]">AI Visibility</span>
          </div>
          <h1 className="display-hero text-[#0a0a0a] mb-6" style={{ textWrap: 'balance' }}>
            How Local Businesses Get Recommended in Google AI Overviews
          </h1>
          <p className="lead-airy text-[#555] mb-8" style={{ textWrap: 'balance' }}>
            AI Overviews now appear at the top of more than 60% of Google searches. For local businesses, that means the first thing a buyer sees is not a list of websites — it&apos;s a short list of recommended businesses. Here&apos;s what determines whether your business is on that list.
          </p>
          <div className="flex items-center gap-3 text-[13px] text-[#6e6e73]">
            <span>By Josh Stanaland</span>
            <span>·</span>
            <span>June 16, 2026</span>
            <span>·</span>
            <span>10 min read</span>
          </div>
        </div>
      </section>

      {/* Article body */}
      <section className="bg-white px-6 py-16">
        <div className="max-w-[720px] mx-auto">

          <div className="text-[17px] leading-[1.75] text-[#333] space-y-6 mb-16">

            <h2 className="text-[26px] font-bold text-[#0a0a0a] mb-4">What are Google AI Overviews?</h2>

            <p>
              Google AI Overviews are AI-generated summaries that appear at the top of Google search results for certain queries. They are generated by Google&apos;s Gemini model and synthesize information from multiple sources, your website, your Google Business Profile, directory listings, review platforms, and other content Google has indexed, into a single answer block. For local queries like &ldquo;best plumber in Wesley Chapel&rdquo; or &ldquo;HVAC company open on Saturday near me,&rdquo; AI Overviews often include a short list of recommended businesses with ratings, hours, and a brief description.
            </p>

            <p>
              For local service businesses, this is the most significant shift in search in over a decade. Traditional SEO put you on a list of ten blue links. AI Overviews give buyers one to three business names. If you are not one of them, you are not in the conversation at all. Read more about <Link href="/resources/blog-end-of-local-seo-ai-visibility" className="text-[#18b5d8] hover:underline">what the end of traditional local SEO means for your business</Link>.
            </p>

            <h2 className="text-[26px] font-bold text-[#0a0a0a] mt-8 mb-4">How Google selects content for AI Overviews</h2>

            <p>
              Google has not published a complete specification for what drives AI Overview inclusion, but the pattern is consistent across industries: AI Overviews favor businesses that are easy for the model to understand, verify, and attribute. That means your data needs to be consistent, your website needs machine-readable structure, and your reputation signals need to be active and recent.
            </p>

            <p>
              The model is doing something different from traditional search ranking. It is not just matching keywords to pages. It is building a structured understanding of what your business does, where it does it, what customers say about it, and whether that information is consistent across sources. A business that tells the same story on its website, its Google Business Profile, Yelp, and dozens of directories is far easier for the model to confidently recommend than one where the name, address, or service description varies across platforms. This is the foundation of <Link href="/resources/blog-seo-old-school-geo-ai-shift" className="text-[#18b5d8] hover:underline">Generative Engine Optimization (GEO)</Link>.
            </p>

            <h2 className="text-[26px] font-bold text-[#0a0a0a] mt-8 mb-4">The five local business signals that matter most</h2>

            <p className="mb-6">
              Through auditing hundreds of local businesses, we&apos;ve identified five categories of signals that consistently separate businesses appearing in AI Overviews from those that don&apos;t. Knowing these signals exist is the easy part. What&apos;s harder is understanding how they interact, how they&apos;re measured, and why fixing one without the others rarely moves the needle.
            </p>

            <div className="space-y-6 mb-6">

              <div className="bg-[#f5f5f7] rounded-[14px] p-7 border border-[#e8e8ed]">
                <h3 className="text-[18px] font-bold text-[#0a0a0a] mb-3">Google Business Profile completeness and activity</h3>
                <p className="text-[15px] text-[#555] leading-relaxed">
                  Your Google Business Profile is the single most important local data source for AI Overviews. The model uses it to verify that your business is real, active, and authoritative in its category. Most GBPs we audit have gaps that aren&apos;t visible to the owner but are immediately apparent to the AI, and those gaps are often the first reason a well-ranked business doesn&apos;t appear in recommendations.
                </p>
              </div>

              <div className="bg-[#f5f5f7] rounded-[14px] p-7 border border-[#e8e8ed]">
                <h3 className="text-[18px] font-bold text-[#0a0a0a] mb-3">Review volume, recency, and response rate</h3>
                <p className="text-[15px] text-[#555] leading-relaxed">
                  Google&apos;s model uses reviews as layered trust signals, and it reads more dimensions of your review profile than most businesses realize. It&apos;s not just about the number of stars. The way reviews accumulate over time, the language customers use, and how the business responds all factor into which queries the AI associates your business with. Learn more about <Link href="/resources/blog-google-reviews-ai-recommendations" className="text-[#18b5d8] hover:underline">how Google reviews become AI recommendations</Link>.
                </p>
              </div>

              <div className="bg-[#f5f5f7] rounded-[14px] p-7 border border-[#e8e8ed]">
                <h3 className="text-[18px] font-bold text-[#0a0a0a] mb-3">Citation consistency across directories</h3>
                <p className="text-[15px] text-[#555] leading-relaxed">
                  AI models cross-reference dozens of data sources to build confidence that your business entity is real and correctly understood. When information varies across platforms, even subtle differences, the model&apos;s confidence drops. Most businesses have more inconsistencies across the web than they know about, and those inconsistencies compound over time. See how <Link href="/resources/blog-ai-map-consistent-business-listings" className="text-[#18b5d8] hover:underline">consistent business listings become your map in the AI era</Link>.
                </p>
              </div>

              <div className="bg-[#f5f5f7] rounded-[14px] p-7 border border-[#e8e8ed]">
                <h3 className="text-[18px] font-bold text-[#0a0a0a] mb-3">Structured data on your website</h3>
                <p className="text-[15px] text-[#555] leading-relaxed">
                  Your website communicates to humans through copy and design. It communicates to AI through structured data. Without machine-readable markup, the model has to infer what your business does, where it operates, and who it serves from unstructured text. It often infers incorrectly, or not at all. Structured data removes that ambiguity, but only when it&apos;s implemented correctly and kept current.
                </p>
              </div>

              <div className="bg-[#f5f5f7] rounded-[14px] p-7 border border-[#e8e8ed]">
                <h3 className="text-[18px] font-bold text-[#0a0a0a] mb-3">Citability of your web content</h3>
                <p className="text-[15px] text-[#555] leading-relaxed">
                  AI Overviews don&apos;t cite homepages. They cite specific passages that the model can extract and attribute with confidence. Most business websites aren&apos;t written to be citable, they&apos;re written to convert a human reader. Those are different problems with different solutions, and confusing the two is one of the most common reasons content-heavy sites still don&apos;t appear in AI recommendations.
                </p>
              </div>

            </div>

            <h2 className="text-[26px] font-bold text-[#0a0a0a] mt-4 mb-4">Why getting this right is harder than it looks</h2>

            <p>
              The five signals above don&apos;t operate independently. Each one affects how the model interprets the others. A strong GBP matters less if your citation data is inconsistent. Structured data matters less if the model can&apos;t trust your entity. Review signals matter less if they don&apos;t align with the queries you need to appear for. The model has to trust your business before it will recommend it, and that trust is built across all five dimensions simultaneously.
            </p>

            <p>
              Businesses that address these signals one at a time, or hand them off to tools that handle each in isolation, rarely see meaningful results. What moves the needle is a coordinated system maintained over time, not a one-time configuration. If you want to know exactly where your business stands across all five signals today, our <Link href="/free-report" className="text-[#18b5d8] hover:underline">free AI visibility audit</Link> shows you what the model sees, where the gaps are, and what it would take to close them.
            </p>

            <h2 className="text-[26px] font-bold text-[#0a0a0a] mt-8 mb-4">A note on timeline</h2>

            <p>
              AI Overviews are not a one-time ranking event. They update continuously as Google recrawls your content and as your GBP signals change. Most businesses with properly configured signals see meaningful movement in AI Overview appearances within 30 to 60 days and significant improvement within 90. The businesses that see the fastest results are the ones with a team actively managing their signals, not the ones who made changes once and waited.
            </p>

          </div>

          {/* FAQ */}
          <div className="mt-4 border-t border-[#e8e8ed] pt-12">
            <h2 className="text-[22px] font-bold text-[#0a0a0a] mb-8">Frequently asked questions</h2>
            <div className="space-y-5">
              {faqs.map((f) => (
                <details key={f.q} className="group bg-[#f5f5f7] rounded-[14px] border border-[#e8e8ed]">
                  <summary className="flex items-center justify-between px-6 py-5 cursor-pointer list-none">
                    <span className="text-[15px] font-semibold text-[#0a0a0a] pr-4">{f.q}</span>
                    <span className="text-[#18b5d8] font-bold text-[18px] shrink-0 group-open:rotate-45 transition-transform duration-150">+</span>
                  </summary>
                  <div className="px-6 pb-5 text-[14px] text-[#555] leading-relaxed">{f.a}</div>
                </details>
              ))}
            </div>
          </div>

          {/* Internal links */}
          <div className="mt-12 border-t border-[#e8e8ed] pt-10">
            <h2 className="text-[18px] font-bold text-[#1d1d1f] mb-5">Related reading</h2>
            <div className="space-y-3">
              <Link href="/resources/blog-seo-old-school-geo-ai-shift" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">SEO Is Old School: Why Your Business Needs GEO to Survive the AI Shift</span>
              </Link>
              <Link href="/resources/blog-google-reviews-ai-recommendations" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">Google Reviews and AI Recommendations: What the Research Shows</span>
              </Link>
              <Link href="/resources/blog-ai-map-consistent-business-listings" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">The AI Map: Why Consistent Business Listings Are the Secret to Being Found</span>
              </Link>
              <Link href="/resources/blog-end-of-local-seo-ai-visibility" className="flex items-center gap-3 group">
                <span className="text-[#18b5d8] font-bold shrink-0">→</span>
                <span className="text-[15px] text-[#333] group-hover:text-[#18b5d8] transition-colors">What the End of Local SEO Means for Your Business</span>
              </Link>
            </div>
          </div>

          {/* CTA */}
          <div className="mt-12 bg-[#0a0a0a] rounded-[14px] px-8 py-10 text-center">
            <h3 className="text-[24px] font-bold text-white mb-4" style={{ textWrap: 'balance' }}>
              Find out where your business stands in Google AI Overviews.
            </h3>
            <p className="text-white/55 text-[15px] mb-8">
              We test your business against 20+ queries across ChatGPT, Gemini, Perplexity, and Google AI Overviews. Your report is ready in 24 hours, then we walk through it with you.
            </p>
            <Link
              href="/free-report"
              className="inline-block bg-[#18b5d8] text-white text-[15px] font-semibold rounded-full px-8 py-4 hover:bg-[#1ec8ee] motion-safe:transition-colors duration-150"
            >
              Get My Free AI Audit
            </Link>
          </div>

        </div>
      </section>
    </>
  )
}
